services:
  - type: web
    name: searxngkingmaster
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn searx.webapp:app -b 0.0.0.0:$PORT
    envVars:
      - key: BASE_URL
        value: https://searxngkingmaster.onrender.com
      - key: SECRET_KEY
        generateValue: true
